site_name: CIRCUITSTATE Docs
site_url: https://docs.circuitstate.io

theme:
  name: material
  logo: assets/images/site/CIRCUITSTATE-R-Emblem-20052024-2.svg
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: custom
      accent: teal

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: custom
      accent: deep purple
  
  # icon:
  #   logo: fontawesome/solid/w
  
  favicon: assets/favicon.ico

  features:
    - navigation.footer
    - navigation.path
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.instant.progress

repo_url: https://github.com/CIRCUITSTATE/Docs
repo_name: Docs

extra_css:
  - assets/stylesheets/extra.css

# extra:
#   social:
#     - icon: simple/youtube
#       link: https://youtube.com/@james-willett
#     - icon: simple/linkedin
#       link: https://linkedin.com/in/willettjames

copyright: Copyright &copy; 2024 James Willett

markdown_extensions:
  - attr_list
  - admonition
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

nav:
  - Welcome: index.md
  - Hardware:
    - Hardware/index.md
    - ESPNut:
      - Hardware/ESPNut/index.md
      - ESPNut-D1:
        - Hardware/ESPNut/ESPNut-D1/index.md
        - R0.1: Hardware/ESPNut/ESPNut-D1/R0.1/index.md
        - R0.3: Hardware/ESPNut/ESPNut-D1/R0.3/index.md

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/tablesort.js
